filter:
  method: "keyword"
  priority_sort_enabled: false
aI_analysis:
  enabled: false
aI_translation:
  enabled: false
display:
  regions:
    ai_analysis: false
notifications:
  enabled: true
  email: