name: TrendRadar Daily Task

on:
  workflow_dispatch:
  schedule:
    # 北京时间 8:30 (UTC 0:30)
    - cron: '30 0 * * *'
    - cron: '30 12 * * *'

jobs:
  run-trend-radar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          EMAIL_FROM: ${{ secrets.MAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.MAIL_PASS }}
          EMAIL_SMTP_SERVER: ${{ secrets.MAIL_HOST }}
          EMAIL_SMTP_PORT: ${{ secrets.MAIL_PORT }}
          EMAIL_TO: ${{ secrets.RECEIVER_EMAIL }}
        run: python -m trendradar
